
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Entry Password;
	
	private global::Gtk.Button LoginRegister;
	
	private global::Gtk.Entry Username;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label label2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Password = new global::Gtk.Entry ();
		this.Password.CanFocus = true;
		this.Password.Name = "Password";
		this.Password.IsEditable = true;
		this.Password.Visibility = false;
		this.Password.InvisibleChar = '•';
		this.fixed1.Add (this.Password);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Password]));
		w1.X = 118;
		w1.Y = 168;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.LoginRegister = new global::Gtk.Button ();
		this.LoginRegister.CanFocus = true;
		this.LoginRegister.Name = "LoginRegister";
		this.LoginRegister.UseUnderline = true;
		this.LoginRegister.Label = global::Mono.Unix.Catalog.GetString ("Login/Register");
		this.fixed1.Add (this.LoginRegister);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.LoginRegister]));
		w2.X = 134;
		w2.Y = 220;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Username = new global::Gtk.Entry ();
		this.Username.CanFocus = true;
		this.Username.Name = "Username";
		this.Username.IsEditable = true;
		this.Username.InvisibleChar = '•';
		this.fixed1.Add (this.Username);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Username]));
		w3.X = 118;
		w3.Y = 89;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Username");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w4.X = 119;
		w4.Y = 58;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w5.X = 118;
		w5.Y = 136;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.LoginRegister.Clicked += new global::System.EventHandler (this.OnLoginRegisterButtonClicked);
	}
}
