
// This file has been generated by the GUI designer. Do not modify.
namespace PT3
{
	public partial class ChatWindow
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Button LogoutChatWindow;
		
		private global::Gtk.Button backtouserlist;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textview7;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TextView textview8;
		
		private global::Gtk.Button button5;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PT3.ChatWindow
			this.Name = "PT3.ChatWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ChatWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child PT3.ChatWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.LogoutChatWindow = new global::Gtk.Button ();
			this.LogoutChatWindow.CanFocus = true;
			this.LogoutChatWindow.Name = "LogoutChatWindow";
			this.LogoutChatWindow.UseUnderline = true;
			this.LogoutChatWindow.Label = global::Mono.Unix.Catalog.GetString ("Logout");
			this.fixed1.Add (this.LogoutChatWindow);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.LogoutChatWindow]));
			w1.X = 309;
			w1.Y = 14;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.backtouserlist = new global::Gtk.Button ();
			this.backtouserlist.CanFocus = true;
			this.backtouserlist.Name = "backtouserlist";
			this.backtouserlist.UseUnderline = true;
			this.backtouserlist.Label = global::Mono.Unix.Catalog.GetString ("Back");
			this.fixed1.Add (this.backtouserlist);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.backtouserlist]));
			w2.X = 13;
			w2.Y = 13;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview7 = new global::Gtk.TextView ();
			this.textview7.WidthRequest = 300;
			this.textview7.HeightRequest = 300;
			this.textview7.CanFocus = true;
			this.textview7.Name = "textview7";
			this.GtkScrolledWindow.Add (this.textview7);
			this.fixed1.Add (this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
			w4.X = 23;
			w4.Y = 91;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textview8 = new global::Gtk.TextView ();
			this.textview8.WidthRequest = 200;
			this.textview8.CanFocus = true;
			this.textview8.Name = "textview8";
			this.GtkScrolledWindow1.Add (this.textview8);
			this.fixed1.Add (this.GtkScrolledWindow1);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow1]));
			w6.X = 20;
			w6.Y = 430;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString ("Send");
			this.fixed1.Add (this.button5);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button5]));
			w7.X = 259;
			w7.Y = 450;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 389;
			this.DefaultHeight = 502;
			this.Show ();
			this.LogoutChatWindow.Clicked += new global::System.EventHandler (this.LogoutButtonChatWindowClicked);
			this.backtouserlist.Clicked += new global::System.EventHandler (this.BackToUserListClicked);
			this.button5.Clicked += new global::System.EventHandler (this.SendButtonClicked);
		}
	}
}
