
// This file has been generated by the GUI designer. Do not modify.
namespace PT3
{
	public partial class Userlist
	{
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Button LogoutUserList;
		
		private global::Gtk.Button ChatButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PT3.Userlist
			this.Name = "PT3.Userlist";
			this.Title = global::Mono.Unix.Catalog.GetString ("Userlist");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child PT3.Userlist.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.LogoutUserList = new global::Gtk.Button ();
			this.LogoutUserList.CanFocus = true;
			this.LogoutUserList.Name = "LogoutUserList";
			this.LogoutUserList.UseUnderline = true;
			this.LogoutUserList.Label = global::Mono.Unix.Catalog.GetString ("Logout");
			this.fixed2.Add (this.LogoutUserList);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.LogoutUserList]));
			w1.X = 11;
			w1.Y = 19;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.ChatButton = new global::Gtk.Button ();
			this.ChatButton.CanFocus = true;
			this.ChatButton.Name = "ChatButton";
			this.ChatButton.UseUnderline = true;
			this.ChatButton.Label = global::Mono.Unix.Catalog.GetString ("Chat ");
			this.fixed2.Add (this.ChatButton);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.ChatButton]));
			w2.X = 269;
			w2.Y = 17;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 362;
			this.DefaultHeight = 512;
			this.Show ();
			this.LogoutUserList.Clicked += new global::System.EventHandler (this.LogoutButtonUserlistClicked);
			this.ChatButton.Clicked += new global::System.EventHandler (this.ChatButtonClicked);
		}
	}
}
