
// This file has been generated by the GUI designer. Do not modify.
namespace PT3.Properties
{
	public partial class chatscreen
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PT3.Properties.chatscreen
			this.Name = "PT3.Properties.chatscreen";
			this.Title = global::Mono.Unix.Catalog.GetString ("chatscreen");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
